spring:
  datasource:
    url: jdbc:h2:mem:ocrdb
    driver-class-name: org.h2.Driver
    username: oc
    password: O123C123

  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  cache:
    type: redis

  redis:
    jedis:
      pool:
        max-idle: 150
        min-idle: 50
    timeout: 60000


management:
  endpoints:
    endpoint:
      health:
        show-details: always
        show-components: always

